language: generic
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-7
before_script:
  - cd Libs
  - FC=gfortran-7
  - ./MakeLibraries.sh
  - cd ..
  - ./MakeMOHIDLagrangian.sh
