language: generic
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-8
before_install:
    - sudo apt-get install libnetcdf-dev -y
before_script:
  - sudo ln -fs /usr/bin/gfortran-8 /usr/bin/gfortran && gfortran --version
  - export FC=gfortran
  - cd Libs  
  - ./MakeLibraries.sh
  - cd ..
  - ./MakeMOHIDLagrangian.sh
