language: generic
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-6
before_script:
  - mkdir build_linux
  - FC=gfortran-6 cmake build_linux
  - cd build_linux
  - make
