language: generic
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-6
before_script:
  - cd Libs
  - ./MakeLibraries.sh
  - cd ..
  - ./MakeMOHIDLagrangian.sh
