language: generic
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-7
before_script:
  - cmake --version
  - export FC=${gfortran-7}
  - FC --version
  - cd Libs  
  - ./MakeLibraries.sh
  - cd ..
  - ./MakeMOHIDLagrangian.sh
