language: generic
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-7
before_script:
  #- cmake --version
  #- sudo ln -fs /usr/bin/gfortran-7 /usr/bin/gfortran && gfortran --version
  - export FC=gfortran
  #- cd Libs  
  #- ./MakeLibraries.sh
  #- cd ..
  - ./MakeMOHIDLagrangian.sh
