name: MOHID-Lagrangian
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - attrs=20.2.0
  - blas=1.0
  - bokeh=2.2.3
  - boost-cpp=1.74.0
  - bzip2=1.0.8
  - c-ares=1.16.1
  - ca-certificates=2020.10.14
  - cairo=1.16.0
  - cartopy=0.18.0
  - certifi=2020.6.20
  - cfitsio=3.470
  - cftime=1.2.1
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.0
  - cloudpickle=1.6.0
  - curl=7.71.1
  - cytoolz=0.11.0
  - dask=2.30.0
  - dask-core=2.30.0
  - distributed=2.30.0
  - double-conversion=3.1.5
  - eigen=3.3.7
  - expat=2.2.10
  - ffmpeg=4.3.1
  - fiona=1.8.17
  - fontconfig=2.13.1
  - freetype=2.10.4
  - freexl=1.0.5
  - fsspec=0.8.3
  - gdal=3.1.4
  - geopandas=0.8.1
  - geos=3.8.1
  - geotiff=1.6.0
  - giflib=5.2.1
  - gl2ps=1.4.2
  - glew=2.1.0
  - glib=2.66.1
  - gmp=6.2.0
  - gnutls=3.6.13
  - h5py=2.10.0
  - hdf4=4.2.13
  - hdf5=1.10.6
  - heapdict=1.0.1
  - icu=67.1
  - intel-openmp=2020.2
  - jinja2=2.11.2
  - jpeg=9d
  - json-c=0.13.1
  - jsoncpp=1.8.4
  - kealib=1.4.13
  - krb5=1.17.1
  - lame=3.100
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libcurl=7.71.1
  - libdap4=3.20.6
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgdal=3.1.4
  - libgfortran-ng=7.3.0
  - libglu=9.0.0
  - libiconv=1.15
  - libkml=1.3.0
  - libllvm10=10.0.1
  - libnetcdf=4.7.4
  - libnghttp2=1.41.0
  - libogg=1.3.2
  - libpng=1.6.37
  - libpq=12.3
  - libspatialindex=1.9.3
  - libspatialite=5.0.0
  - libssh2=1.9.0
  - libstdcxx-ng=9.1.0
  - libtheora=1.1.1
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp-base=1.1.0
  - libxcb=1.14
  - libxml2=2.9.10
  - llvmlite=0.34.0
  - locket=0.2.0
  - loguru=0.5.3
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - msgpack-python=1.0.0
  - munch=2.5.0
  - ncurses=6.2
  - netcdf4=1.5.4
  - nettle=3.4.1
  - numba=0.51.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openh264=2.1.1
  - openjpeg=2.3.1
  - openssl=1.1.1h
  - packaging=20.4
  - pandas=1.1.3
  - partd=1.1.0
  - pcre=8.44
  - pillow=8.0.1
  - pip=20.2.4
  - pixman=0.38.0
  - poppler=0.89.0
  - poppler-data=0.4.10
  - postgresql=12.3
  - proj=7.1.1
  - psutil=5.7.2
  - pugixml=1.10
  - pyparsing=2.4.7
  - pyproj=2.6.1.post1
  - pyshp=2.1.2
  - python=3.7.9
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2020.1
  - pyyaml=5.3.1
  - readline=8.0
  - rtree=0.9.4
  - setuptools=50.3.0
  - shapely=1.7.1
  - six=1.15.0
  - sortedcontainers=2.2.2
  - sqlite=3.33.0
  - tbb=2020.3
  - tbb-devel=2020.3
  - tblib=1.7.0
  - tiledb=2.1.2
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.0.4
  - tqdm=4.50.2
  - typing_extensions=3.7.4.3
  - tzcode=2020a
  - utfcpp=3.1.2
  - vtk=9.0.1
  - wheel=0.35.1
  - x264=1!152.20180806
  - xarray=0.16.1
  - xerces-c=3.2.3
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.0
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - zict=2.0.0
  - zlib=1.2.11
  - zstd=1.4.5
